name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Enhancements'
    labels: ['enhancement', 'feature']
  - title: 'Bug Fixes'
    labels: ['bug', 'fix']
  - title: 'Docs'
    labels: ['documentation']
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  ## Changes

  $CHANGES

  ## Thanks

  $CONTRIBUTORS
