name: Sanity

on:
  push:
  pull_request:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Verify Python files compile
        run: |
          python -m py_compile __init__.py code_v2.py

      - name: Verify Qt UI file parses
        run: |
          python - << 'PY'
          import xml.etree.ElementTree as ET
          ET.parse('protliginteract.ui')
          print('UI parsed OK')
          PY

      - name: Basic repo checks
        run: |
          test -f README.md
          test -f requirements.txt
          echo 'Repo contains expected files.'
